/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study_resources;

import arraylist_handler.ArrayListHandler;
import javax.swing.JDialog;
import javax.swing.JLabel;

/**
 *
 * @author jdev1
 */
public class Add_Study_Resource extends javax.swing.JFrame {

    /**
     * Creates new form Add_Study_Resource
     */
    public Add_Study_Resource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiltle_label = new javax.swing.JLabel();
        enter_resource_name_label = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        back_to_resource_management_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        enter_resource_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiltle_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tiltle_label.setForeground(new java.awt.Color(242, 242, 242));
        tiltle_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiltle_label.setText("Add Study Resource");
        getContentPane().add(tiltle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 412, -1));

        enter_resource_name_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enter_resource_name_label.setForeground(new java.awt.Color(242, 242, 242));
        enter_resource_name_label.setText("Enter Resource Name");
        getContentPane().add(enter_resource_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, -1));

        submit_button.setBackground(new java.awt.Color(23, 20, 20));
        submit_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submit_button.setForeground(new java.awt.Color(242, 242, 242));
        submit_button.setText("Submit");
        submit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(submit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        back_to_resource_management_button.setBackground(new java.awt.Color(23, 20, 20));
        back_to_resource_management_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back_to_resource_management_button.setForeground(new java.awt.Color(242, 242, 242));
        back_to_resource_management_button.setText("Back to Resource Mangement");
        back_to_resource_management_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_resource_management_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(back_to_resource_management_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enter_resource_textfield.setBackground(new java.awt.Color(23, 20, 20));
        enter_resource_textfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enter_resource_textfield.setForeground(new java.awt.Color(242, 242, 242));
        enter_resource_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_resource_textfieldActionPerformed(evt);
            }
        });
        jPanel1.add(enter_resource_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 206, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_to_resource_management_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_resource_management_buttonMouseClicked
        // TODO add your handling code here:
        Resource_Management resource_management = new Resource_Management();
        this.setVisible(false);
        resource_management.setVisible(true);
    }//GEN-LAST:event_back_to_resource_management_buttonMouseClicked

    private void submit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit_buttonMouseClicked
        // TODO add your handling code here:
        
           
        String resource_information = enter_resource_textfield.getText();
      
        
        ArrayListHandler.addResource(resource_information);
        
         JDialog dialog = new JDialog(this, "Resource entered");
                dialog.add(new JLabel("Your resource has been entered into your task management."));
                dialog.setSize(350, 100);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);
                dialog.setResizable(false);
        // Informs the user that they have entered a duplicate class
        
        if(ArrayListHandler.getResourceMatched() == true){
            JDialog dialog1 = new JDialog(this, "Resource Duplicated");
                dialog1.add(new JLabel("Your have entered a duplicated resoource."));
                dialog1.setSize(250, 100);
                dialog1.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog1.setVisible(true);
                dialog1.setResizable(false);
        }
        
             
    }//GEN-LAST:event_submit_buttonMouseClicked

    private void enter_resource_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_resource_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_resource_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Study_Resource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_resource_management_button;
    private javax.swing.JLabel enter_resource_name_label;
    private javax.swing.JTextField enter_resource_textfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submit_button;
    private javax.swing.JLabel tiltle_label;
    // End of variables declaration//GEN-END:variables
}
