/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study_resources;

import main.vsa_dashboard;
import study_tasks.Task_Management;

/**
 *
 * @author jdev1
 */
public class Resource_Management extends javax.swing.JFrame {

    /**
     * Creates new form Resource_Management
     */
    public Resource_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiltle_label = new javax.swing.JLabel();
        add_study_resource = new javax.swing.JButton();
        search_study_resource = new javax.swing.JButton();
        view_study_resource = new javax.swing.JButton();
        back_to_dashboard = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiltle_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tiltle_label.setForeground(new java.awt.Color(242, 242, 242));
        tiltle_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiltle_label.setText("Resource Management");
        getContentPane().add(tiltle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 399, -1));

        add_study_resource.setBackground(new java.awt.Color(23, 20, 20));
        add_study_resource.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_study_resource.setForeground(new java.awt.Color(242, 242, 242));
        add_study_resource.setText("Add Study Resource");
        add_study_resource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_study_resourceMouseClicked(evt);
            }
        });
        getContentPane().add(add_study_resource, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 94, 179, -1));

        search_study_resource.setBackground(new java.awt.Color(23, 20, 20));
        search_study_resource.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        search_study_resource.setForeground(new java.awt.Color(242, 242, 242));
        search_study_resource.setText("Search/View Study Resource");
        search_study_resource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_study_resourceMouseClicked(evt);
            }
        });
        search_study_resource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_study_resourceActionPerformed(evt);
            }
        });
        getContentPane().add(search_study_resource, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 135, -1, -1));

        view_study_resource.setBackground(new java.awt.Color(23, 20, 20));
        view_study_resource.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        view_study_resource.setForeground(new java.awt.Color(242, 242, 242));
        view_study_resource.setText("View Study Resources");
        view_study_resource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_study_resourceMouseClicked(evt);
            }
        });
        getContentPane().add(view_study_resource, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 176, 179, -1));

        back_to_dashboard.setBackground(new java.awt.Color(23, 20, 20));
        back_to_dashboard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_to_dashboard.setForeground(new java.awt.Color(242, 242, 242));
        back_to_dashboard.setText("Back to DashBoard");
        back_to_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_dashboardMouseClicked(evt);
            }
        });
        getContentPane().add(back_to_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, 149, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_study_resourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_study_resourceMouseClicked
        // TODO add your handling code here:
        Add_Study_Resource study_resource = new  Add_Study_Resource();
        this.setVisible(false);
        study_resource.setVisible(true);
    }//GEN-LAST:event_add_study_resourceMouseClicked

    private void search_study_resourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_study_resourceMouseClicked
        // TODO add your handling code here:
        View_Study_Resource view_resource = new  View_Study_Resource();
        this.setVisible(false);
        view_resource.setVisible(true);
    }//GEN-LAST:event_search_study_resourceMouseClicked

    private void view_study_resourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_study_resourceMouseClicked
        // TODO add your handling code here:
        View_Resources study_resource = new  View_Resources();
        this.setVisible(false);
        study_resource.setVisible(true);
    }//GEN-LAST:event_view_study_resourceMouseClicked

    private void back_to_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_dashboardMouseClicked
        // TODO add your handling code here:
        vsa_dashboard dash = new vsa_dashboard();
        this.setVisible(false);
        dash.setVisible(true);
    }//GEN-LAST:event_back_to_dashboardMouseClicked

    private void search_study_resourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_study_resourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_study_resourceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resource_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_study_resource;
    private javax.swing.JButton back_to_dashboard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton search_study_resource;
    private javax.swing.JLabel tiltle_label;
    private javax.swing.JButton view_study_resource;
    // End of variables declaration//GEN-END:variables
}
