/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study_resources;

import arraylist_handler.ArrayListHandler;
import javax.swing.JDialog;
import javax.swing.JLabel;
import study_tasks.Edit_Task_Information;

/**
 *
 * @author jdev1
 */
public class View_Study_Resource extends javax.swing.JFrame {

    /**
     * Creates new form View_Study_Resource
     */
    public View_Study_Resource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_label = new javax.swing.JLabel();
        enter_resource_label = new javax.swing.JLabel();
        resource_search_textfield = new javax.swing.JTextField();
        back_to_resource_management = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title_label.setForeground(new java.awt.Color(242, 242, 242));
        title_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_label.setText("Search Resource");
        getContentPane().add(title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 399, -1));

        enter_resource_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enter_resource_label.setForeground(new java.awt.Color(242, 242, 242));
        enter_resource_label.setText("Enter Resource Name");
        getContentPane().add(enter_resource_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 399, -1));

        resource_search_textfield.setBackground(new java.awt.Color(23, 20, 20));
        resource_search_textfield.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resource_search_textfield.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(resource_search_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 399, -1));

        back_to_resource_management.setBackground(new java.awt.Color(23, 20, 20));
        back_to_resource_management.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_to_resource_management.setForeground(new java.awt.Color(242, 242, 242));
        back_to_resource_management.setText("Back to Resource Management");
        back_to_resource_management.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_resource_managementMouseClicked(evt);
            }
        });
        getContentPane().add(back_to_resource_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, -1, -1));

        search_button.setBackground(new java.awt.Color(23, 20, 20));
        search_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        search_button.setForeground(new java.awt.Color(242, 242, 242));
        search_button.setText("Search");
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 276, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_to_resource_managementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_resource_managementMouseClicked
        // TODO add your handling code here:
        Resource_Management resource_management = new Resource_Management();
        this.setVisible(false);
        resource_management.setVisible(true);
    }//GEN-LAST:event_back_to_resource_managementMouseClicked

    private void search_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseClicked
        // TODO add your handling code here:
        ArrayListHandler.searchResource(resource_search_textfield.getText());
       
        if(ArrayListHandler.getResourceMatched() == true){
             JDialog dialog = new JDialog(this, "Resource View");
                dialog.add(new JLabel("Resource Found: " + resource_search_textfield.getText()));
                dialog.setSize(450, 100);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);
                dialog.setResizable(false);
            
        }
        else if(ArrayListHandler.getResourceMatched() == false){
             JDialog dialog = new JDialog(this, "Resource not in Task Management");
                dialog.add(new JLabel("Your resource is not in resource management."));
                dialog.setSize(450, 100);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);
                dialog.setResizable(false);
            
        }
       
        else if ( ArrayListHandler.getResourceEmpty() == true){
            JDialog dialog = new JDialog(this, "Resource Management is empty");
                dialog.add(new JLabel("The Resource list is empty."));
                dialog.setSize(450, 100);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);
                dialog.setResizable(false);
            
        }
        
     
        
    }//GEN-LAST:event_search_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Study_Resource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Study_Resource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_resource_management;
    private javax.swing.JLabel enter_resource_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField resource_search_textfield;
    private javax.swing.JButton search_button;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
