/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study_resources;

import arraylist_handler.ArrayListHandler;


/**
 *
 * @author jdev1
 */
public class View_Resources extends javax.swing.JFrame {

    /**
     * Creates new form View_Resources
     */
    public View_Resources() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiltle_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resource_table = new javax.swing.JTable();
        back_to_ResourceMngmt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tiltle_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tiltle_label.setForeground(new java.awt.Color(242, 242, 242));
        tiltle_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiltle_label.setText("Study Resources");
        getContentPane().add(tiltle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        resource_table.setBackground(new java.awt.Color(23, 20, 20));
        resource_table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        resource_table.setForeground(new java.awt.Color(242, 242, 242));
        resource_table.setModel(new javax.swing.table.DefaultTableModel(
            ArrayListHandler.table_resource_Display(),
            new String [] {
                "Resource List"
            }
        ));
        jScrollPane1.setViewportView(resource_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 414, 247));

        back_to_ResourceMngmt.setBackground(new java.awt.Color(23, 20, 20));
        back_to_ResourceMngmt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_to_ResourceMngmt.setForeground(new java.awt.Color(242, 242, 242));
        back_to_ResourceMngmt.setText("Back to Resource Management");
        back_to_ResourceMngmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_ResourceMngmtMouseClicked(evt);
            }
        });
        getContentPane().add(back_to_ResourceMngmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 291, 408, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_to_ResourceMngmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_ResourceMngmtMouseClicked

        // TODO add your handling code here:
        Resource_Management resource_management = new Resource_Management();
        this.setVisible(false);
        resource_management.setVisible(true);
    }//GEN-LAST:event_back_to_ResourceMngmtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Resources().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_ResourceMngmt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable resource_table;
    private javax.swing.JLabel tiltle_label;
    // End of variables declaration//GEN-END:variables
}
