/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study_tasks;



import arraylist_handler.ArrayListHandler;
import javax.swing.JDialog;
import javax.swing.JLabel;
import main.vsa_dashboard;

/**
 *
 * @author jdev1
 */
public class Task_Management extends javax.swing.JFrame {

    /**
     * Creates new form Schedule_Management
     */
    
    public Task_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schedule_managementTitle = new javax.swing.JLabel();
        back_to_dashbaord = new javax.swing.JButton();
        edit_schedule = new javax.swing.JButton();
        create_schedule = new javax.swing.JButton();
        delete_schedule = new javax.swing.JButton();
        display_schedule = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schedule_managementTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        schedule_managementTitle.setForeground(new java.awt.Color(242, 242, 242));
        schedule_managementTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        schedule_managementTitle.setText("Task Management");
        getContentPane().add(schedule_managementTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        back_to_dashbaord.setBackground(new java.awt.Color(23, 20, 20));
        back_to_dashbaord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back_to_dashbaord.setForeground(new java.awt.Color(242, 242, 242));
        back_to_dashbaord.setText("Back To Dashboard");
        back_to_dashbaord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_dashbaordMouseClicked(evt);
            }
        });
        getContentPane().add(back_to_dashbaord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, -1, -1));

        edit_schedule.setBackground(new java.awt.Color(23, 20, 20));
        edit_schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit_schedule.setForeground(new java.awt.Color(242, 242, 242));
        edit_schedule.setText("Edit Task");
        edit_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_scheduleMouseClicked(evt);
            }
        });
        getContentPane().add(edit_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 388, -1));

        create_schedule.setBackground(new java.awt.Color(23, 20, 20));
        create_schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        create_schedule.setForeground(new java.awt.Color(242, 242, 242));
        create_schedule.setText("Create Task");
        create_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                create_scheduleMouseClicked(evt);
            }
        });
        create_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_scheduleActionPerformed(evt);
            }
        });
        getContentPane().add(create_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 388, -1));

        delete_schedule.setBackground(new java.awt.Color(23, 20, 20));
        delete_schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete_schedule.setForeground(new java.awt.Color(242, 242, 242));
        delete_schedule.setText("Delete Tasks");
        delete_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_scheduleMouseClicked(evt);
            }
        });
        getContentPane().add(delete_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 171, 388, -1));

        display_schedule.setBackground(new java.awt.Color(23, 20, 20));
        display_schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        display_schedule.setForeground(new java.awt.Color(242, 242, 242));
        display_schedule.setText("Display Task");
        display_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_scheduleMouseClicked(evt);
            }
        });
        display_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_scheduleActionPerformed(evt);
            }
        });
        getContentPane().add(display_schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 132, 388, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_to_dashbaordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_dashbaordMouseClicked
        // TODO add your handling code here:
        
        vsa_dashboard dash = new vsa_dashboard();
        this.setVisible(false);
        dash.setVisible(true);
    }//GEN-LAST:event_back_to_dashbaordMouseClicked

    private void display_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_scheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_display_scheduleActionPerformed

    private void create_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_scheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_scheduleActionPerformed

    private void create_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_scheduleMouseClicked
        // TODO add your handling code here:
        Create_Task create_schedule = new Create_Task ();
        this.setVisible(false);
        create_schedule.setVisible(true);
    }//GEN-LAST:event_create_scheduleMouseClicked

    private void delete_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_scheduleMouseClicked
        // TODO add your handling code here:
        ArrayListHandler.deleteTasks();
        JDialog dialog = new JDialog(this, "Task Deletion Confirmation");
                dialog.add(new JLabel("Your Task has been deleted."));
                dialog.setSize(350, 100);
                dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                dialog.setVisible(true);
                dialog.setResizable(false);
        
    }//GEN-LAST:event_delete_scheduleMouseClicked

    private void edit_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_scheduleMouseClicked
        // TODO add your handling code here:
        Edit_Task create_schedule = new Edit_Task ();
        this.setVisible(false);
        create_schedule.setVisible(true);
    }//GEN-LAST:event_edit_scheduleMouseClicked

    private void display_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_scheduleMouseClicked
        // TODO add your handling code here:
        Display_Task display_schedule = new Display_Task ();
        this.setVisible(false);
        display_schedule.setVisible(true);
        
    }//GEN-LAST:event_display_scheduleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_dashbaord;
    private javax.swing.JButton create_schedule;
    private javax.swing.JButton delete_schedule;
    private javax.swing.JButton display_schedule;
    private javax.swing.JButton edit_schedule;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel schedule_managementTitle;
    // End of variables declaration//GEN-END:variables
}
