/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progress_tracking;

import main.vsa_dashboard;

/**
 *
 * @author jdev1
 */
public class Progress_Management extends javax.swing.JFrame {

    /**
     * Creates new form Progress_Management
     */
    public Progress_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edit_button = new javax.swing.JButton();
        display_study_progress = new javax.swing.JButton();
        back_to_dashboard = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Progress Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        edit_button.setBackground(new java.awt.Color(23, 20, 20));
        edit_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edit_button.setForeground(new java.awt.Color(242, 242, 242));
        edit_button.setText("Edit Study Progress");
        edit_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(edit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 65, 164, -1));

        display_study_progress.setBackground(new java.awt.Color(23, 20, 20));
        display_study_progress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        display_study_progress.setForeground(new java.awt.Color(242, 242, 242));
        display_study_progress.setText("Display Study Progress");
        display_study_progress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                display_study_progressMouseClicked(evt);
            }
        });
        getContentPane().add(display_study_progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 136, 164, -1));

        back_to_dashboard.setBackground(new java.awt.Color(23, 20, 20));
        back_to_dashboard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_to_dashboard.setForeground(new java.awt.Color(242, 242, 242));
        back_to_dashboard.setText("Back to Dashboard");
        back_to_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_to_dashboardMouseClicked(evt);
            }
        });
        getContentPane().add(back_to_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_to_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_to_dashboardMouseClicked
        // TODO add your handling code here:
        vsa_dashboard dash = new vsa_dashboard();
        this.setVisible(false);
        dash.setVisible(true);
    }//GEN-LAST:event_back_to_dashboardMouseClicked

    private void edit_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_buttonMouseClicked
        // TODO add your handling code here:
        Edit_Progress edit_progress = new Edit_Progress ();
        this.setVisible(false);
        edit_progress.setVisible(true);
    }//GEN-LAST:event_edit_buttonMouseClicked

    private void display_study_progressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_display_study_progressMouseClicked
        // TODO add your handling code here:
        Progress_Display progress_display = new  Progress_Display();
        this.setVisible(false);
        progress_display.setVisible(true);
    }//GEN-LAST:event_display_study_progressMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progress_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progress_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progress_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progress_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Progress_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_to_dashboard;
    private javax.swing.JButton display_study_progress;
    private javax.swing.JButton edit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
